In [14]:
import pandas as pd
import numpy as np

In [15]:
#  Read CSVs
file1 = "SCDB_2018_02_caseCentered_Citation.csv"
file2 = "landmark.csv"
file3 = "currentcases_cleaned.csv"

SC_data = pd.read_csv(file1, encoding = "latin1")
LM_data = pd.read_csv(file2)
CC_data = pd.read_csv(file3)

# LM_data
# SC_data.head()
CC_data.head()

caseId                                           caseName  term  \
0  2018-054                             Flowers v. Mississippi  2018   
1  2018-011  Washingston State Dept Licensing v. Cougar Den...  2018   
2  2018-031            Franchise Tax Board California v. Hyatt  2018   
3  2018-052       American Legion v. American Humanist Society  2018   
4  2018-066                              Rucho v. Common Cause  2018   

   decisionDirection  precedentAlteration  issueArea  lawType  caseOriginState  
0                  2                    0          2        2               29  
1                  2                    0         10        8               56  
2                  1                    1          9        2                6  
3                  1                    0          3        1               25  
4                  1                    0          2        1               38

In [16]:
# Select Landmark cases from Supreme Court data set
caseIds = LM_data["CaseId"]
# caseIds
LM_SC = SC_data[SC_data["caseId"].isin(caseIds)]
LM_SC.head()

caseId     docketId    caseIssuesId             voteId dateDecision  \
879   1953-069  1953-069-01  1953-069-01-01  1953-069-01-01-01    5/17/1954   
1792  1960-133  1960-133-01  1960-133-01-01  1960-133-01-01-01    6/19/1961   
1974  1962-058  1962-058-01  1962-058-01-01  1962-058-01-01-01    3/18/1963   
2513  1965-122  1965-122-01  1965-122-01-01  1965-122-01-01-01    6/13/1966   
2919  1968-043  1968-043-01  1968-043-01-01  1968-043-01-01-01    2/24/1969   

      decisionType        usCite         sctCite           ledCite  \
879              1  347 U.S. 483   74 S. Ct. 686  98 L. Ed. 2d 873   
1792             1  367 U.S. 643  81 S. Ct. 1684  6 L. Ed. 2d 1081   
1974             1  372 U.S. 335   83 S. Ct. 792   9 L. Ed. 2d 799   
2513             1  384 U.S. 436  86 S. Ct. 1602  16 L. Ed. 2d 694   
2919             1  393 U.S. 503   89 S. Ct. 733  21 L. Ed. 2d 731   

                 lexisCite    ...     authorityDecision1  authorityDecision2  \
879   1954 U.S. LEXIS 2094    ...                    2.0                 NaN   
1792   1961 U.S. LEXIS 812    ...                    2.0                 NaN   
1974  1963 U.S. LEXIS 1942    ...                    2.0                 NaN   
2513  1966 U.S. LEXIS 2817    ...                    2.0                 NaN   
2919  1969 U.S. LEXIS 2443    ...                    2.0                 NaN   

     lawType lawSupp lawMinor majOpinWriter majOpinAssigner  splitVote  \
879      2.0   231.0      NaN          90.0            90.0          1   
1792     2.0   205.0      NaN          88.0            90.0          1   
1974     2.0   214.0      NaN          78.0            90.0          1   
2513     2.0   210.0      NaN          90.0            90.0          1   
2919     2.0   200.0      NaN          97.0            90.0          1   

      majVotes  minVotes  
879          9         0  
1792         6         3  
1974         9         0  
2513         5         4  
2919         7         2  

[5 rows x 53 columns]

In [17]:
LM_SC_data = LM_SC[["caseId","caseName", "term", "precedentAlteration", "issueArea", "lawType", "caseOriginState", "decisionDirection"]]
LM_SC_data.head()

caseId                                           caseName  term  \
879   1953-069  BROWN et al. v. BOARD OF EDUCATION OF TOPEKA e...  1953   
1792  1960-133                                       MAPP v. OHIO  1960   
1974  1962-058         GIDEON v. WAINWRIGHT, CORRECTIONS DIRECTOR  1962   
2513  1965-122                                 MIRANDA v. ARIZONA  1965   
2919  1968-043  TINKER et al. v. DES MOINES INDEPENDENT COMMUN...  1968   

      precedentAlteration  issueArea  lawType  caseOriginState  \
879                   1.0        2.0      2.0              NaN   
1792                  1.0        1.0      2.0             41.0   
1974                  1.0        1.0      2.0             12.0   
2513                  1.0        1.0      2.0              4.0   
2919                  0.0        3.0      2.0              NaN   

      decisionDirection  
879                 2.0  
1792                2.0  
1974                2.0  
2513                2.0  
2919                2.0

In [18]:
# replace NaN with 9 (no legal provision) for lawType and 60 (United States) for caseOriginState
LM_SC_data = LM_SC_data.fillna(value={"lawType": 9, "caseOriginState": 60})
LM_SC_data

caseId                                           caseName  term  \
879   1953-069  BROWN et al. v. BOARD OF EDUCATION OF TOPEKA e...  1953   
1792  1960-133                                       MAPP v. OHIO  1960   
1974  1962-058         GIDEON v. WAINWRIGHT, CORRECTIONS DIRECTOR  1962   
2513  1965-122                                 MIRANDA v. ARIZONA  1965   
2919  1968-043  TINKER et al. v. DES MOINES INDEPENDENT COMMUN...  1968   
3528  1972-048  ROE et al. v. WADE, DISTRICT ATTORNEY OF DALLA...  1972   
3838  1973-172  UNITED STATES v. NIXON, PRESIDENT OF THE UNITE...  1973   
4499  1977-147   REGENTS OF THE UNIVERSITY OF CALIFORNIA v. BAKKE  1977   
5517  1984-022                             NEW JERSEY v. T. L. O.  1984   
6005  1987-019  HAZELWOOD SCHOOL DISTRICT et al. v. KUHLMEIER ...  1987   
6263  1988-124                                   TEXAS v. JOHNSON  1988   

      precedentAlteration  issueArea  lawType  caseOriginState  \
879                   1.0        2.0      2.0             60.0   
1792                  1.0        1.0      2.0             41.0   
1974                  1.0        1.0      2.0             12.0   
2513                  1.0        1.0      2.0              4.0   
2919                  0.0        3.0      2.0             60.0   
3528                  0.0        5.0      2.0             60.0   
3838                  0.0        1.0      9.0             60.0   
4499                  0.0        2.0      2.0              6.0   
5517                  0.0        1.0      2.0             35.0   
6005                  0.0        3.0      2.0             60.0   
6263                  0.0        3.0      2.0             51.0   

      decisionDirection  
879                 2.0  
1792                2.0  
1974                2.0  
2513                2.0  
2919                2.0  
3528                2.0  
3838                1.0  
4499                1.0  
5517                1.0  
6005                1.0  
6263                2.0

In [19]:
CC_data = CC_data[["caseId","caseName", "term", "precedentAlteration", "issueArea", "lawType", "caseOriginState", "decisionDirection"]]
CC_data["caseName"] = CC_data['caseName'].str.upper()
CC_data

caseId                                           caseName  term  \
0  2018-054                             FLOWERS V. MISSISSIPPI  2018   
1  2018-011  WASHINGSTON STATE DEPT LICENSING V. COUGAR DEN...  2018   
2  2018-031            FRANCHISE TAX BOARD CALIFORNIA V. HYATT  2018   
3  2018-052       AMERICAN LEGION V. AMERICAN HUMANIST SOCIETY  2018   
4  2018-066                              RUCHO V. COMMON CAUSE  2018   
5  2018-024                                  DAWSON V. STEAGER  2018   

   precedentAlteration  issueArea  lawType  caseOriginState  decisionDirection  
0                    0          2        2               29                  2  
1                    0         10        8               56                  2  
2                    1          9        2                6                  1  
3                    0          3        1               25                  1  
4                    0          2        1               38                  1  
5                    0         10        3               57                  2

In [20]:
cases_df = pd.concat([LM_SC_data, CC_data], axis=0)
cases_df.reset_index(drop=True, inplace=True)
cases_df

caseId                                           caseName  term  \
0   1953-069  BROWN et al. v. BOARD OF EDUCATION OF TOPEKA e...  1953   
1   1960-133                                       MAPP v. OHIO  1960   
2   1962-058         GIDEON v. WAINWRIGHT, CORRECTIONS DIRECTOR  1962   
3   1965-122                                 MIRANDA v. ARIZONA  1965   
4   1968-043  TINKER et al. v. DES MOINES INDEPENDENT COMMUN...  1968   
5   1972-048  ROE et al. v. WADE, DISTRICT ATTORNEY OF DALLA...  1972   
6   1973-172  UNITED STATES v. NIXON, PRESIDENT OF THE UNITE...  1973   
7   1977-147   REGENTS OF THE UNIVERSITY OF CALIFORNIA v. BAKKE  1977   
8   1984-022                             NEW JERSEY v. T. L. O.  1984   
9   1987-019  HAZELWOOD SCHOOL DISTRICT et al. v. KUHLMEIER ...  1987   
10  1988-124                                   TEXAS v. JOHNSON  1988   
11  2018-054                             FLOWERS V. MISSISSIPPI  2018   
12  2018-011  WASHINGSTON STATE DEPT LICENSING V. COUGAR DEN...  2018   
13  2018-031            FRANCHISE TAX BOARD CALIFORNIA V. HYATT  2018   
14  2018-052       AMERICAN LEGION V. AMERICAN HUMANIST SOCIETY  2018   
15  2018-066                              RUCHO V. COMMON CAUSE  2018   
16  2018-024                                  DAWSON V. STEAGER  2018   

    precedentAlteration  issueArea  lawType  caseOriginState  \
0                   1.0        2.0      2.0             60.0   
1                   1.0        1.0      2.0             41.0   
2                   1.0        1.0      2.0             12.0   
3                   1.0        1.0      2.0              4.0   
4                   0.0        3.0      2.0             60.0   
5                   0.0        5.0      2.0             60.0   
6                   0.0        1.0      9.0             60.0   
7                   0.0        2.0      2.0              6.0   
8                   0.0        1.0      2.0             35.0   
9                   0.0        3.0      2.0             60.0   
10                  0.0        3.0      2.0             51.0   
11                  0.0        2.0      2.0             29.0   
12                  0.0       10.0      8.0             56.0   
13                  1.0        9.0      2.0              6.0   
14                  0.0        3.0      1.0             25.0   
15                  0.0        2.0      1.0             38.0   
16                  0.0       10.0      3.0             57.0   

    decisionDirection  
0                 2.0  
1                 2.0  
2                 2.0  
3                 2.0  
4                 2.0  
5                 2.0  
6                 1.0  
7                 1.0  
8                 1.0  
9                 1.0  
10                2.0  
11                2.0  
12                2.0  
13                1.0  
14                1.0  
15                1.0  
16                2.0

In [8]:
cases_df.to_csv("cases_for_prediction.csv")

In [13]:
# grab unique values to include in one-hot encoding later
unique_term = cases_df["term"].unique()
unique_issueArea = cases_df["issueArea"].unique()
unique_caseOriginState = cases_df["caseOriginState"].unique()
unique_lawType = cases_df["lawType"].unique()

print(unique_term)
print(unique_lawType)
print(unique_issueArea)
print(unique_caseOriginState)

[1953 1960 1962 1965 1968 1972 1973 1977 1984 1987 1988 2018]
[2. 9. 8. 1. 3.]
[ 2.  1.  3.  5. 10.  9.]
[60. 41. 12.  4.  6. 35. 51. 29. 56. 25. 38. 57.]
